{
 "title": "Alerts2",
 "description": "Alerts from prometheus alertmanager.",
 "tags": [
  "App",
  "Alerts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,1m,5m,1h,6h,1d" },
   { "name": "service", "label": "service", "query": "label_values(ALERTS, service)" },
   { "name": "job", "label": "job", "query": "label_values(ALERTS, job)" },
   {
    "name": "alertname",
    "label": "alertname",
    "query": "label_values(ALERTS, alertname)"
   },
   { "name": "alertstate", "label": "alertstate", "query": "firing, pending" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{ service=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{service=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"warning\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Max  Load Average 1m",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (node_load1{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Min Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable{service=~\"$service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Tcp Established",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_netstat_Tcp_CurrEstab{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Prometheus HTTP Request Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{job=\"prometheus\"}[5m])) /  sum(irate(http_request_duration_microseconds_count{job=\"prometheus\"}[5m]))"
    }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Current alerts table",
   "type": "table",
   "description": "Таблица с последними алертами",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "ALERTS{alertname=~\"$alertname\", alertstate=~\"$alertstate\"}",
     "labelSelector": "*",
     "legendFormat": "service: {{service}} instance: {{instance}}  alertname: {{alertname}}  ",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Alerts Graph: instance alertname",
   "type": "graph",
   "description": "График алертов: имя хоста (instance) имя алерта (alertname)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "count(ALERTS{ service=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\"} == 1)  by (instance,alertname)",
     "legendFormat": "{{instance}}  {{alertname}}"
    }
   ]
  },
  {
   "title": "Current warnings table",
   "type": "table",
   "description": "Таблица с последними предупреждениями",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "count(ALERTS{ service=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\"} == 1) by (instance,alertname,service,job)",
     "legendFormat": "service: {{service}} instance: {{instance}}  alertname: {{alertname}}   service: {{service}}"
    }
   ]
  },
  {
   "title": "Warnings Graph: instance alertname",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "count(ALERTS{ service=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"warning\"} == 1)  by (instance,alertname)",
     "legendFormat": "{{instance}} {{alertname}}"
    }
   ]
  }
 ]
}